*** Settings ***
Library    OperatingSystem
Library    SeleniumLibrary
Library    Collections
Resource        ..${/}resource${/}identifiers${/}main.resource
Resource        ..${/}resource${/}keywords${/}main.resource
Resource        ..${/}resource${/}test_scripts${/}main.resource
Resource        ..${/}resource${/}test_data${/}main.resource
Resource        ..${/}resource${/}variables${/}main.resource